### PR TITLE
Error messages fixed

### PR DESCRIPTION
**Pull request by fferrara**
Hi mate, thanks for the great fork! I really needed a rectangular crop!

When I used the crop with ng-file-upload, I experienced some error messages `image is null`, probably due to the asynchronous image loading.
It was really fast to fix and I would like to deploy my project using your component and bower.
If you had a little time, please merge it! ;)

### CODE REVIEW

**Comment by fferrara** [comment]
I realized my changes broke the `updateResultImage()` function. I'll work better on that.

**Comment by joncodo** [comment]
:+1:

**Comment by fferrara** [comment]
My bad. I used the wrong name for a variable. Now the code should be fine!

**Comment by joncodo** [comment]
You know what I really need done? I need this project brought back to the original structure with all the changes in there as well. You could go to the original project and clone it. Then just bring in all the changes that we have written here. Up for that PR?

**Comment by fferrara** [comment]
You mean the original project -> https://github.com/alexk111/ngImgCrop ?

**Pull request merged**
